table Bio_met_pot
	lineageTag: 479c446f-b25d-4ac5-ae94-39c7a8c50ae3

	measure Potential_selected = ```
			
			CONCATENATEX(
			    VALUES('Bio_met_pot'[Biomethane_potential]), 
			    'Bio_met_pot'[Biomethane_potential], 
			    ", "
			)
			```
		lineageTag: f8388fc3-4f3a-41af-a6b3-704ddd0c16da

	column Biomethane_potential
		dataType: string
		lineageTag: 7a11e29b-c1c8-457a-9307-3525ddc6c1cd
		summarizeBy: none
		sourceColumn: Biomethane_potential

		annotation SummarizationSetBy = Automatic

	partition Bio_met_pot = m
		mode: import
		source =
				let
				    Origem = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WCslIzS9KLclMTsxRitUB8lOTM/IgvFgA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Biomethane_potential = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Origem,{{"Biomethane_potential", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

