table Municipality
	lineageTag: 3a950d42-0321-4c19-bbcd-45f5ad941ffc

	measure Municipio_selecionado = ```
			IF (
			        ISFILTERED('Municipality'[Municipality]),
			        CONCATENATEX(
			            VALUES('Municipality'[Municipality]), 
			            'Municipality'[Municipality], 
			            ", "
			        ),
			        "Mainland Portugal"
			    )
			```
		lineageTag: adf46a59-42fe-4329-b185-cd2dd4d73a61

	measure Nuts3_selecionado =
			
			IF(
			    ISFILTERED('Municipality'[Municipality]),
			    CONCATENATEX(
			        VALUES('Municipality'[Nuts3]),   -- unique Nuts3 only
			        'Municipality'[Nuts3],
			        ", "
			    ),
			    "Mainland Portugal"
			)
		lineageTag: 2f31a4db-dbc2-45a0-8b40-b232ebb71576

	column Municipality
		dataType: string
		lineageTag: 2ba3401e-7ee4-4ce4-bb7b-65242c2abfd4
		dataCategory: City
		summarizeBy: none
		sourceColumn: Municipality

		annotation SummarizationSetBy = Automatic

	column Nuts2
		dataType: string
		lineageTag: d9c11831-a5b2-410a-a884-c1964ec1fd15
		dataCategory: Country
		summarizeBy: none
		sourceColumn: Nuts2

		annotation SummarizationSetBy = Automatic

	column Nuts3
		dataType: string
		lineageTag: 13244cf3-e413-4bfb-9177-e7a3e5b51fa1
		dataCategory: Country
		summarizeBy: none
		sourceColumn: Nuts3

		annotation SummarizationSetBy = Automatic

	column Municipality_lower
		dataType: string
		lineageTag: 01bfc07b-e079-402e-bc32-3659227c173a
		summarizeBy: none
		sourceColumn: Municipality_lower

		annotation SummarizationSetBy = Automatic

	column Índice
		dataType: int64
		formatString: 0
		lineageTag: 257bf3f2-d841-4d8a-87d4-1e8a9efa8031
		summarizeBy: none
		sourceColumn: Índice

		annotation SummarizationSetBy = Automatic

	column Location_Map =
			
			'Municipality'[Municipality] & " (municipality), Portugal"
		lineageTag: b61d9ebf-48ea-4eea-861e-5acd80f0bb80
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Indice_nuts2
		dataType: int64
		formatString: 0
		lineageTag: d80fd11f-112a-4d15-aca6-5c5e11b27c0b
		summarizeBy: none
		sourceColumn: Indice_nuts2

		annotation SummarizationSetBy = Automatic

	column Indice_nuts3
		dataType: int64
		formatString: 0
		lineageTag: 6c013bc9-62c7-455b-af0c-3bb410492882
		summarizeBy: sum
		sourceColumn: Indice_nuts3

		annotation SummarizationSetBy = Automatic

	hierarchy 'Nuts2 Hierarquia'
		lineageTag: b1a35ac7-76d4-4eb1-893d-2198f643923d

		level Nuts2
			lineageTag: d8e586e8-a5d7-42fb-b714-edb032b0a6e9
			column: Nuts2

		level Nuts3
			lineageTag: b0728ea1-9e17-474f-8ff5-d562d91acc03
			column: Nuts3

		level Municipality
			lineageTag: 661f1a89-23e0-41d2-a25a-8e6fcb65f0d8
			column: Municipality

	partition Municipality = m
		mode: import
		source =
				let
				    Origem = Excel.Workbook(File.Contents("C:\Users\fcpla\OneDrive\BioRede\biomethane_potential_cleaned.xlsx"), null, true),
				    Municipality_Sheet = Origem{[Item="Municipality",Kind="Sheet"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(Municipality_Sheet,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}}),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Tipo Alterado", [PromoteAllScalars=true]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Municipality", type text}, {"Nuts2", type text}, {"Nuts3", type text}, {"Municipality_lower", type text}}),
				    #"Valor Substituído" = Table.ReplaceValue(#"Tipo Alterado1","Santa Maria da Feira","Feira",Replacer.ReplaceText,{"Municipality"}),
				    #"Índice Adicionado" = Table.AddIndexColumn(#"Valor Substituído", "Índice", 1, 1, Int64.Type),
				    #"Consultas Intercaladas" = Table.NestedJoin(#"Índice Adicionado", {"Nuts2"}, Nuts2, {"Nuts2"}, "Nuts2.1", JoinKind.LeftOuter),
				    #"Nuts2.1 Expandida" = Table.ExpandTableColumn(#"Consultas Intercaladas", "Nuts2.1", {"Indice_nuts2"}, {"Indice_nuts2"}),
				    #"Consultas Intercaladas1" = Table.NestedJoin(#"Nuts2.1 Expandida", {"Nuts3"}, Nuts3, {"Nuts3"}, "Nuts3.1", JoinKind.LeftOuter),
				    #"Nuts3.1 Expandida" = Table.ExpandTableColumn(#"Consultas Intercaladas1", "Nuts3.1", {"Indice_nuts3"}, {"Indice_nuts3"})
				in
				    #"Nuts3.1 Expandida"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

